export const PHOTOS_IS_FETCHING = "PHOTOS_IS_FETCHING";
export const PHOTOS_FETCH_DATA_SUCCESS = "PHOTOS_FETCH_DATA_SUCCESS";
export const PHOTOS_IS_UPLOADING = "PHOTOS_IS_UPLOADING";
export const PHOTOS_IS_UPLOADED = "PHOTOS_IS_UPLOADED";
export const PHOTOS_UPLOAD_ERRORED = "PHOTOS_UPLOAD_ERRORED";
export const PHOTOS_HAS_ERRORED = "PHOTOS_HAS_ERRORED";
export const PHOTOS_CHANGE_PAGE = "PHOTOS_CHANGE_PAGE";
export const PHOTOS_MODAL_IS_OPEN = "PHOTOS_MODAL_IS_OPEN";
